<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="A360-Automation" name="scripts.Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy" tests="5" failures="0" timestamp="16 Nov 2022 08:28:37 GMT" time="48.180" errors="4">
  <testcase name="Issues_Should_Not_Be_Display_For_Reviewer_Test" time="41.605" classname="scripts.Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy">
    <error type="org.openqa.selenium.TimeoutException" message="Expected condition failed: waiting for visibility of [[ChromeDriver: chrome on WINDOWS (0d108a49930e40080f64cc3a56ab9172)] -&gt; xpath: //td[@class=&#039;dataTables_empty&#039;]] (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: &#039;3.141.0&#039;, revision: &#039;2ecb7d9a&#039;, time: &#039;2018-10-31T20:09:30&#039;
System info: host: &#039;A360-Automation&#039;, ip: &#039;10.3.0.5&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_201&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.107, chrome: {chromedriverVersion: 106.0.5249.61 (511755355844..., userDataDir: C:\Users\audit360\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:60203}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 0d108a49930e40080f64cc3a56ab9172">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of [[ChromeDriver: chrome on WINDOWS (0d108a49930e40080f64cc3a56ab9172)] -> xpath: //td[@class='dataTables_empty']] (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:09:30'
System info: host: 'A360-Automation', ip: '10.3.0.5', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.107, chrome: {chromedriverVersion: 106.0.5249.61 (511755355844..., userDataDir: C:\Users\audit360\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:60203}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 0d108a49930e40080f64cc3a56ab9172
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at pom.IssuesPageTest.VerifyNoDataAvailableInTableIsDisplayed(IssuesPageTest.java:331)
	at scripts.Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy.Issues_Should_Not_Be_Display_For_Reviewer_Test(Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy.java:2528)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Issues_Should_Not_Be_Display_For_Reviewer_Test -->
  <testcase name="Closing_And_Reopening_The_Issue_By_Auditor_Test" time="0.000" classname="scripts.Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy">
    <error type="java.lang.Throwable" message="Method Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy.Closing_And_Reopening_The_Issue_By_Auditor_Test()[pri:0, instance:scripts.Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy@50f8360d] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy.Closing_And_Reopening_The_Issue_By_Auditor_Test()[pri:0, instance:scripts.Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy@50f8360d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Closing_And_Reopening_The_Issue_By_Auditor_Test -->
  <testcase name="Issues_Should_Not_Be_Display_For_Respondent_Test" time="0.000" classname="scripts.Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy">
    <error type="java.lang.Throwable" message="Method Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy.Issues_Should_Not_Be_Display_For_Respondent_Test()[pri:0, instance:scripts.Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy@50f8360d] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy.Issues_Should_Not_Be_Display_For_Respondent_Test()[pri:0, instance:scripts.Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy@50f8360d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Issues_Should_Not_Be_Display_For_Respondent_Test -->
  <testcase name="Create_Audit_Type_Page_Test" time="6.575" classname="scripts.Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy"/>
  <testcase name="Bulk_Resolve_Issues_By_AuditeeUser_Test" time="0.000" classname="scripts.Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy">
    <error type="java.lang.Throwable" message="Method Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy.Bulk_Resolve_Issues_By_AuditeeUser_Test()[pri:0, instance:scripts.Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy@50f8360d] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy.Bulk_Resolve_Issues_By_AuditeeUser_Test()[pri:0, instance:scripts.Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy@50f8360d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Bulk_Resolve_Issues_By_AuditeeUser_Test -->
</testsuite> <!-- scripts.Scenario1RespondentAndAuditeeReviewerWorkflowHasBeenEliminatedButAuditeeSignoffIsEnabledCopy -->
